package absyn;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Stack;

/**
 * CodeGenerator - Generates TM assembly code from C- AST
 * Implements visitor pattern to traverse AST and emit TM instructions
 */
public class CodeGenerator implements AbsynVisitor {
    
    // ========== Output and Tracking ==========
    private PrintWriter out;
    private int emitLoc = 0;           // Current instruction location
    private int highEmitLoc = 0;       // Highest location emitted so far
    
    // ========== Register Constants ==========
    private static final int ac = 0;   // Accumulator
    private static final int ac1 = 1;  // Secondary accumulator  
    private static final int gp = 6;   // Global pointer
    private static final int fp = 5;   // Frame pointer
    private static final int pc = 7;   // Program counter
    
    // ========== Frame Offsets ==========
    private static final int ofpFO = 0;    // Old frame pointer offset
    private static final int retFO = -1;   // Return address offset
    private static final int initFO = -2;  // Initial offset for params/locals
    
    // ========== Memory Management ==========
    private int globalOffset = 0;      // Offset for global variables (grows negative)
    private int mainEntry = -1;        // Entry point for main function
    private int inputEntry = -1;       // Entry point for input function
    private int outputEntry = -1;      // Entry point for output function
    
    // ========== Symbol Tracking (replaces AST field additions) ==========
    private HashMap<String, Integer> varOffsets = new HashMap<>();     // Variable offsets
    private HashMap<String, Integer> varLevels = new HashMap<>();      // Nest levels (0=global, 1=local)
    private HashMap<String, Integer> funcAddresses = new HashMap<>();  // Function entry addresses
    private HashMap<String, Integer> arraySizes = new HashMap<>();     // Array sizes
    // Stack for saving/restoring scopes
    private Stack<HashMap<String, Integer>> offsetStack = new Stack<>();
    private Stack<HashMap<String, Integer>> levelStack = new Stack<>();
    private Stack<HashMap<String, Integer>> sizeStack = new Stack<>();
    // Map from function name to list of instruction locations needing backpatching
    private HashMap<String, ArrayList<Integer>> forwardCalls = new HashMap<>();
    
    // ========== Context Tracking (replaces isAddr parameter) ==========
    private boolean computingAddress = false;  // True when computing LHS of assignment
    
    // ========== Constructor ==========
    public CodeGenerator(PrintWriter output) {
        this.out = output;
    }
    
    // ========== Main Generation Entry Point ==========
    /**
     * Main entry point for code generation
     * Called from CM.java after successful semantic analysis
     */
    public void generate(Absyn program) {
        emitComment("C-Minus Compilation to TM Code");
        emitComment("File: [generated by compiler]");
        
        // Generate standard prelude
        generatePrelude();
        
        // Generate I/O routines
        generateIORoutines();
        
        // Generate code for the program (all declarations)
        program.accept(this, 0);
        
        // Generate finale (call main and halt)
        generateFinale();
    }
    
    // ========== Prelude and I/O Routines ==========
    
    private void generatePrelude() {
        emitComment("Standard prelude:");
        emitRM("LD", gp, 0, ac, "load gp with maxaddress");
        emitRM("LDA", fp, 0, gp, "copy gp to fp");
        emitRM("ST", ac, 0, ac, "clear location 0");
        emitComment("Jump around i/o routines here");
        
        // Skip to be backpatched after I/O routines
        int savedLoc = emitSkip(1);
        
        emitComment("code for input routine");
        inputEntry = emitLoc;
        emitRM("ST", ac, retFO, fp, "store return");
        emitRO("IN", ac, 0, 0, "input");
        emitRM("LD", pc, retFO, fp, "return to caller");
        
        emitComment("code for output routine");
        outputEntry = emitLoc;
        emitRM("ST", ac, retFO, fp, "store return");
        emitRM("LD", ac, initFO, fp, "load output value");
        emitRO("OUT", ac, 0, 0, "output");
        emitRM("LD", pc, retFO, fp, "return to caller");
        
        // Backpatch jump around I/O
        int savedLoc2 = emitLoc;
        emitBackup(savedLoc);
        emitRM_Abs("LDA", pc, savedLoc2, "jump around i/o code");
        emitRestore();
        
        emitComment("End of standard prelude.");
    }
    
    private void generateIORoutines() {
        // Already generated in prelude
        // Input and output entries are saved in inputEntry and outputEntry
    }
    
    private void generateFinale() {
        if (mainEntry == -1) {
            emitComment("ERROR: No main function found!");
            return;
        }
        
        emitRM("ST", fp, globalOffset + ofpFO, fp, "push ofp");
        emitRM("LDA", fp, globalOffset, fp, "push frame");
        emitRM("LDA", ac, 1, pc, "load ac with ret ptr");
        emitRM_Abs("LDA", pc, mainEntry, "jump to main loc");
        emitRM("LD", fp, ofpFO, fp, "pop frame");
        emitComment("End of execution.");
        emitRO("HALT", 0, 0, 0, "");
    }
    
    // ========== Code Emission Helper Methods ==========
    
    /**
     * Emit RO (Register-Only) instruction
     * Format: opcode r,s,t
     */
    private void emitRO(String op, int r, int s, int t, String comment) {
        out.printf("%3d: %5s %d,%d,%d", emitLoc, op, r, s, t);
        if (!comment.isEmpty()) {
            out.print("\t" + comment);
        }
        out.println();
        emitLoc++;
        if (highEmitLoc < emitLoc) {
            highEmitLoc = emitLoc;
        }
    }
    
    /**
     * Emit RM (Register-Memory) instruction
     * Format: opcode r,d(s)
     */
    private void emitRM(String op, int r, int d, int s, String comment) {
        out.printf("%3d: %5s %d,%d(%d)", emitLoc, op, r, d, s);
        if (!comment.isEmpty()) {
            out.print("\t" + comment);
        }
        out.println();
        emitLoc++;
        if (highEmitLoc < emitLoc) {
            highEmitLoc = emitLoc;
        }
    }
    
    /**
     * Emit RM instruction with absolute address
     * Calculates relative offset from current PC
     */
    private void emitRM_Abs(String op, int r, int a, String comment) {
        out.printf("%3d: %5s %d,%d(%d)", emitLoc, op, r, a - (emitLoc + 1), pc);
        if (!comment.isEmpty()) {
            out.print("\t" + comment);
        }
        out.println();
        emitLoc++;
        if (highEmitLoc < emitLoc) {
            highEmitLoc = emitLoc;
        }
    }
    
    /**
     * Skip 'distance' instruction slots (for backpatching)
     * Returns the location of the first skipped instruction
     */
    private int emitSkip(int distance) {
        int loc = emitLoc;
        emitLoc += distance;
        if (highEmitLoc < emitLoc) {
            highEmitLoc = emitLoc;
        }
        return loc;
    }
    
    /**
     * Backup to a specific location for backpatching
     */
    private void emitBackup(int loc) {
        if (loc > highEmitLoc) {
            emitComment("BUG in emitBackup");
        }
        emitLoc = loc;
    }
    
    /**
     * Restore to highEmitLoc after backpatching
     */
    private void emitRestore() {
        emitLoc = highEmitLoc;
    }
    
    /**
     * Emit a comment line
     */
    private void emitComment(String comment) {
        out.println("* " + comment);
    }
    
    // ========== Visitor Methods ==========
    public void visit(DecList decList, int level) {
        while (decList != null) {
            if (decList.head != null) {
                decList.head.accept(this, level);
            }
            decList = decList.tail;
        }
    }
    
    public void visit(SimpleDec dec, int level) {
        // Allocate space for simple variable
        if (level == 0) {
            // Global variable
            varOffsets.put(dec.name, globalOffset);
            varLevels.put(dec.name, 0);
            globalOffset--;
            emitComment("allocating global var: " + dec.name);
        } else {
            // Local variable - offset will be set by function context
            // For now, we'll handle this in FunctionDec
        }
    }
    
    public void visit(ArrayDec dec, int level) {
        emitComment("allocating array: " + dec.name);
        
        if (level == 0) {
            int size = dec.size;
            
            // Store size one slot above where base will be
            globalOffset--;  // size slot
            emitRM("LDC", ac, size, 0, "load array size");
            emitRM("ST", ac, globalOffset, gp, "store array size");
            
            globalOffset--;  // base slot = x[0]
            varOffsets.put(dec.name, globalOffset);  // base points to x[0]
            varLevels.put(dec.name, 0);
            arraySizes.put(dec.name, size);
            
            globalOffset -= (size - 1);  // remaining elements x[1]..x[n-1]
            
            emitComment("array " + dec.name + " size " + size + " allocated at offset " + globalOffset);
        } else {
            // Local arrays are handled in FunctionDec
        }
    }
    
    public void visit(FunctionDec dec, int level) {
        // Save current scope
        offsetStack.push(new HashMap<>(varOffsets));
        levelStack.push(new HashMap<>(varLevels));
        sizeStack.push(new HashMap<>(arraySizes));

        emitComment("processing function: " + dec.name);
        
        // Emit jump around function body (will be backpatched)
        emitComment("jump around function body here");
        int jumpLoc = emitSkip(1);
        
        // Function entry - store return address
        int funcEntry = emitLoc;

        // Save function entry point
        funcAddresses.put(dec.name, emitLoc);

        // Backpatch any forward calls to this function
        if (forwardCalls.containsKey(dec.name)) {
            for (int callLoc : forwardCalls.get(dec.name)) {
                emitBackup(callLoc);
                emitRM_Abs("LDA", pc, funcEntry, "jump to fun loc (backpatched)");
            }
            emitRestore();
            forwardCalls.remove(dec.name);
        }

        // Check if this is main
        if (dec.name.equals("main")) {
            mainEntry = emitLoc;
        }

        emitRM("ST", ac, retFO, fp, "store return");
        
        // Process parameters - allocate offsets starting at initFO
        int paramOffset = initFO;
        if (dec.params != null && dec.params.head != null) {
            VarDecList params = dec.params;
            while (params != null) {
                if (params.head != null) {
                    String paramName = "";
                    
                    if (params.head instanceof SimpleDec) {
                        SimpleDec simpleParam = (SimpleDec) params.head;
                        paramName = simpleParam.name;
                        if (!paramName.isEmpty()) {
                            varOffsets.put(paramName, paramOffset);
                            varLevels.put(paramName, 1);
                            paramOffset--;
                        }
                    } else if (params.head instanceof ArrayDec) {
                        ArrayDec arrayParam = (ArrayDec) params.head;
                        paramName = arrayParam.name;
                        if (!paramName.isEmpty()) {
                            // Array parameter: store base address
                            varOffsets.put(paramName, paramOffset);
                            varLevels.put(paramName, 1);
                            // Note: size is passed with the array, stored one location below base
                            arraySizes.put(paramName, -1); // Size unknown at compile time
                            paramOffset--;
                        }
                    }
                }
                params = params.tail;
            }
        }
        
        // Process local declarations in body
        int localOffset = paramOffset; // Continue after parameters
        if (dec.body instanceof CompoundExp) {
            CompoundExp compound = (CompoundExp) dec.body;
            if (compound.decs != null) {
                VarDecList locals = compound.decs;
                while (locals != null) {
                    if (locals.head != null && locals.head instanceof SimpleDec) {
                        SimpleDec localVar = (SimpleDec) locals.head;
                        emitComment("processing local var: " + localVar.name);
                        varOffsets.put(localVar.name, localOffset);
                        varLevels.put(localVar.name, 1);
                        localOffset--;
                    } else if (locals.head != null && locals.head instanceof ArrayDec) {
                        ArrayDec localArr = (ArrayDec) locals.head;
                        emitComment("processing local array: " + localArr.name);
                        // Store size one slot above base
                        emitRM("LDC", ac, localArr.size, 0, "load local array size");
                        emitRM("ST", ac, localOffset, fp, "store local array size");
                        localOffset--;  // size slot used
                        // Base points to element[0]
                        varOffsets.put(localArr.name, localOffset);
                        varLevels.put(localArr.name, 1);
                        arraySizes.put(localArr.name, localArr.size);
                        localOffset -= localArr.size;  // element slots
                    }
                    locals = locals.tail;
                }
            }
        }
        
        // Process function body
        if (dec.body != null) {
            dec.body.accept(this, localOffset); // Pass frame offset for temps
        }
        
        // Function epilogue - return to caller
        emitRM("LD", pc, retFO, fp, "return to caller");
        
        // Backpatch jump around function
        int savedLoc = emitLoc;
        emitBackup(jumpLoc);
        emitRM_Abs("LDA", pc, savedLoc, "jump around fn body");
        emitRestore();

        // Restore previous scope
        varOffsets = offsetStack.pop();
        varLevels = levelStack.pop();
        arraySizes = sizeStack.pop();
        
        emitComment("<- fundecl");
    }

    // Helper method to calculate frame size
    private int calculateFrameSize(FunctionDec dec) {
        int size = 2; // ofp + return address
        
        // Count parameters
        if (dec.params != null && dec.params.head != null) {
            if (dec.params.head instanceof SimpleDec) {
                SimpleDec firstParam = (SimpleDec) dec.params.head;
                if (!firstParam.name.isEmpty()) {
                    VarDecList params = dec.params;
                    while (params != null) {
                        size++;
                        params = params.tail;
                    }
                }
            }
        }
        
        // Count local variables
        if (dec.body instanceof CompoundExp) {
            CompoundExp compound = (CompoundExp) dec.body;
            if (compound.decs != null) {
                VarDecList locals = compound.decs;
                while (locals != null) {
                    size++;
                    locals = locals.tail;
                }
            }
        }
        
        // Add space for temps (estimate: 10 for Phase 1)
        size += 10;
        
        return size;
    }
    
    public void visit(FunctionProtoDec dec, int level) {
        // Phase 5 (mutual recursion)
    }
    
    public void visit(VarDecList decList, int level) {
        while (decList != null) {
            if (decList.head != null) {
                decList.head.accept(this, level);
            }
            decList = decList.tail;
        }
    }
    
        public void visit(ExpList expList, int level) {
        while (expList != null) {
            if (expList.head != null) {
                expList.head.accept(this, level);
            }
            expList = expList.tail;
        }
    }
    
    public void visit(CompoundExp exp, int level) {
        emitComment("-> compound statement");
        
        // Process any local declarations in this block (e.g. vars inside while/if)
        int localLevel = level;
        if (exp.decs != null) {
            VarDecList locals = exp.decs;
            while (locals != null) {
                if (locals.head != null && locals.head instanceof SimpleDec) {
                    SimpleDec localVar = (SimpleDec) locals.head;
                    emitComment("processing nested local var: " + localVar.name);
                    varOffsets.put(localVar.name, localLevel);
                    varLevels.put(localVar.name, 1);
                    localLevel--;
                }
                locals = locals.tail;
            }
        }
        
        // Process statements using updated level
        if (exp.exps != null) {
            exp.exps.accept(this, localLevel);
        }
        
        emitComment("<- compound statement");
    }
    
    public void visit(IntExp exp, int level) {
        emitComment("-> constant");
        emitRM("LDC", ac, exp.value, 0, "load const");
        emitComment("<- constant");
    }
    
    public void visit(BoolExp exp, int level) {
        emitComment("-> constant");
        // true = 1, false = 0
        emitRM("LDC", ac, exp.value ? 1 : 0, 0, "load bool const");
        emitComment("<- constant");
    }
    
    public void visit(VarExp exp, int level) {
        if (exp.variable != null) {
            exp.variable.accept(this, level);
        }
    }
    
    public void visit(SimpleVar var, int level) {
        emitComment("-> id");
        emitComment("looking up id: " + var.name);
        
        Integer offset = varOffsets.get(var.name);
        Integer nestLevel = varLevels.get(var.name);
        
        if (offset == null || nestLevel == null) {
            emitComment("ERROR: Undefined variable " + var.name);
            return;
        }
        
        if (computingAddress) {
            // Load address of variable
            if (nestLevel == 0) {
                emitRM("LDA", ac, offset, gp, "load id address");
            } else {
                emitRM("LDA", ac, offset, fp, "load id address");
            }
        } else {
            // Load value of variable
            if (nestLevel == 0) {
                emitRM("LD", ac, offset, gp, "load id value");
            } else {
                emitRM("LD", ac, offset, fp, "load id value");
            }
        }
        
        emitComment("<- id");
    }
    
    public void visit(IndexVar var, int level) {
        emitComment("-> indexed var");

        Integer baseOffset = varOffsets.get(var.name);
        Integer nestLevel = varLevels.get(var.name);
        Integer arraySize = arraySizes.get(var.name);

        if (baseOffset == null || nestLevel == null) {
            emitComment("ERROR: Undefined array " + var.name);
            return;
        }

        boolean wasComputingAddress = computingAddress;
        computingAddress = false;

        if (var.index != null) {
            var.index.accept(this, level - 1);
        }

        computingAddress = wasComputingAddress;

        // Save index to temp
        emitRM("ST", ac, level - 1, fp, "save index");

        // Load base address of array into ac
        if (nestLevel == 0) {
            emitRM("LDA", ac, baseOffset, gp, "load array base");
        } else if (arraySize != null && arraySize == -1) {
            emitRM("LD", ac, baseOffset, fp, "load array base from param");
        } else {
            emitRM("LDA", ac, baseOffset, fp, "load array base");
        }

        // Move base address to ac1, reload index into ac
        emitRM("LDA", ac1, 0, ac, "copy base address to ac1");
        emitRM("LD", ac, level - 1, fp, "reload index for bounds check");

        // Check index >= 0 (skip 3 instructions if OK)
        emitRM("JGE", ac, 3, pc, "skip if index >= 0");
        emitRM("LDC", ac, -1000000, 0, "out of range below error code");
        emitRO("OUT", ac, 0, 0, "output error code");
        emitRO("HALT", 0, 0, 0, "halt on bounds error");

        // Load size from base (base is in ac1)
        emitRM("LD", ac1, 1, ac1, "load size from base+1");

        // Check index < size (skip 3 instructions if OK)
        emitRO("SUB", ac, ac, ac1, "index - size");
        emitRM("JLT", ac, 3, pc, "skip if index < size");
        emitRM("LDC", ac, -2000000, 0, "out of range above error code");
        emitRO("OUT", ac, 0, 0, "output error code");
        emitRO("HALT", 0, 0, 0, "halt on bounds error");

        // Recompute element address
        if (nestLevel == 0) {
            emitRM("LDA", ac, baseOffset, gp, "reload array base");
        } else if (arraySize != null && arraySize == -1) {
            emitRM("LD", ac, baseOffset, fp, "reload array base from param");
        } else {
            emitRM("LDA", ac, baseOffset, fp, "reload array base");
        }
        emitRM("LD", ac1, level - 1, fp, "reload index");
        emitRO("SUB", ac, ac, ac1, "compute element address");

        if (!wasComputingAddress) {
            emitRM("LD", ac, 0, ac, "load array element");
        }

        emitComment("<- indexed var");
    }
    
    public void visit(CallExp exp, int level) {
        emitComment("-> call of function: " + exp.func);
        
        // Special handling for input() and output()
        if (exp.func.equals("input")) {
            // Call input routine
            emitRM("ST", fp, level, fp, "push ofp");
            emitRM("LDA", fp, level, fp, "push frame");
            emitRM("LDA", ac, 1, pc, "load ac with ret ptr");
            emitRM_Abs("LDA", pc, inputEntry, "jump to fun loc");
            emitRM("LD", fp, ofpFO, fp, "pop frame");
        } else if (exp.func.equals("output")) {
            // Evaluate argument (result in ac)
            if (exp.args != null && exp.args.head != null) {
                exp.args.head.accept(this, level - 1);
            }
            
            // ac now contains the argument value
            // Push new frame and store argument at initFO (-2)
            emitRM("ST", fp, level, fp, "push ofp");
            emitRM("LDA", fp, level, fp, "push frame");
            emitRM("ST", ac, initFO, fp, "store arg val");
            emitRM("LDA", ac, 1, pc, "load ac with ret ptr");
            emitRM_Abs("LDA", pc, outputEntry, "jump to fun loc");
            emitRM("LD", fp, ofpFO, fp, "pop frame");
        } else {
            // Regular function call
            
            // Count arguments
            int argCount = 0;
            if (exp.args != null) {
                ExpList args = exp.args;
                while (args != null) {
                    argCount++;
                    args = args.tail;
                }
            }
            
            // Calculate frame offset for the call
            // frameOffset = current level - (ofp + ret + params) - space for temps
            int frameOffset = level - argCount - 2;
            
            // Evaluate and store arguments relative to NEW frame
            int argOffset = initFO;  // Start at -2
            if (exp.args != null) {
                ExpList args = exp.args;
                int argIndex = 0;
                while (args != null) {
                    if (args.head != null) {
                        // Each argument gets separate temp space
                        int argTempLevel = frameOffset + initFO - argIndex - 1;
                        
                        // Check if this argument is an array being passed by reference
                        boolean isArrayArg = false;
                        if (args.head instanceof VarExp) {
                            VarExp ve = (VarExp) args.head;
                            if (ve.variable instanceof SimpleVar) {
                                SimpleVar sv = (SimpleVar) ve.variable;
                                if (arraySizes.containsKey(sv.name)) {
                                    isArrayArg = true;
                                }
                            }
                        }
                        
                        if (isArrayArg) {
                            // Determine if this is a global array or a forwarded array parameter
                            SimpleVar sv = (SimpleVar)((VarExp)args.head).variable;
                            Integer argNestLevel = varLevels.get(sv.name);
                            Integer argArraySize = arraySizes.get(sv.name);
                            
                            if (argNestLevel != null && argNestLevel == 1 && 
                                argArraySize != null && argArraySize == -1) {
                                // Array parameter being forwarded: load the stored base address
                                computingAddress = false;
                                args.head.accept(this, argTempLevel);
                            } else {
                                // Global or local array: pass its base address
                                computingAddress = true;
                                args.head.accept(this, argTempLevel);
                                computingAddress = false;
                            }
                        } else {
                            args.head.accept(this, argTempLevel);
                        }
                        
                        emitRM("ST", ac, frameOffset + argOffset, fp, "store arg val");
                        argOffset--;
                        argIndex++;
                    }
                    args = args.tail;
                }
            }
            // Get function address
            Integer funcAddr = funcAddresses.get(exp.func);

            // Call sequence
            emitRM("ST", fp, frameOffset + ofpFO, fp, "push ofp");
            emitRM("LDA", fp, frameOffset, fp, "push frame");
            emitRM("LDA", ac, 1, pc, "load ac with ret ptr");

            if (funcAddr == null) {
                // Forward reference: emit placeholder and record for backpatching
                int callLoc = emitSkip(1);
                if (!forwardCalls.containsKey(exp.func)) {
                    forwardCalls.put(exp.func, new ArrayList<Integer>());
                }
                forwardCalls.get(exp.func).add(callLoc);
                emitComment("forward call to: " + exp.func + " at loc " + callLoc);
            } else {
                emitRM_Abs("LDA", pc, funcAddr, "jump to fun loc");
            }
            emitRM("LD", fp, ofpFO, fp, "pop frame");
        }
        emitComment("<- call");
    }
    
    public void visit(OpExp exp, int level) {
        emitComment("-> op");
        
        // Visit left operand
        if (exp.left != null) {
            exp.left.accept(this, level - 1);
        }
        // Save left result to temp
        emitRM("ST", ac, level - 1, fp, "op: push left");
        
        // Visit right operand
        if (exp.right != null) {
            exp.right.accept(this, level - 2);
        }
        
        // Load left back into ac1
        emitRM("LD", ac1, level - 1, fp, "op: load left");
        
        // Perform operation (result in ac)
        switch (exp.op) {
            case OpExp.PLUS:
                emitRO("ADD", ac, ac1, ac, "op +");
                break;
                
            case OpExp.MINUS:
                emitRO("SUB", ac, ac1, ac, "op -");
                break;
                
            case OpExp.TIMES:
                emitRO("MUL", ac, ac1, ac, "op *");
                break;
                
            case OpExp.OVER:
                emitRO("DIV", ac, ac1, ac, "op /");
                break;
                
            case OpExp.LT:
                emitRO("SUB", ac, ac1, ac, "op <");
                emitRM("JLT", ac, 2, pc, "br if true");
                emitRM("LDC", ac, 0, 0, "false case");
                emitRM("LDA", pc, 1, pc, "unconditional jmp");
                emitRM("LDC", ac, 1, 0, "true case");
                break;
                
            case OpExp.LE:
                emitRO("SUB", ac, ac1, ac, "op <=");
                emitRM("JLE", ac, 2, pc, "br if true");
                emitRM("LDC", ac, 0, 0, "false case");
                emitRM("LDA", pc, 1, pc, "unconditional jmp");
                emitRM("LDC", ac, 1, 0, "true case");
                break;
                
            case OpExp.GT:
                emitRO("SUB", ac, ac1, ac, "op >");
                emitRM("JGT", ac, 2, pc, "br if true");
                emitRM("LDC", ac, 0, 0, "false case");
                emitRM("LDA", pc, 1, pc, "unconditional jmp");
                emitRM("LDC", ac, 1, 0, "true case");
                break;
                
            case OpExp.GE:
                emitRO("SUB", ac, ac1, ac, "op >=");
                emitRM("JGE", ac, 2, pc, "br if true");
                emitRM("LDC", ac, 0, 0, "false case");
                emitRM("LDA", pc, 1, pc, "unconditional jmp");
                emitRM("LDC", ac, 1, 0, "true case");
                break;
                
            case OpExp.EQ:
                emitRO("SUB", ac, ac1, ac, "op ==");
                emitRM("JEQ", ac, 2, pc, "br if true");
                emitRM("LDC", ac, 0, 0, "false case");
                emitRM("LDA", pc, 1, pc, "unconditional jmp");
                emitRM("LDC", ac, 1, 0, "true case");
                break;
                
            case OpExp.NE:
                emitRO("SUB", ac, ac1, ac, "op !=");
                emitRM("JNE", ac, 2, pc, "br if true");
                emitRM("LDC", ac, 0, 0, "false case");
                emitRM("LDA", pc, 1, pc, "unconditional jmp");
                emitRM("LDC", ac, 1, 0, "true case");
                break;
                
            case OpExp.AND:
                // Both operands in ac1 (left) and ac (right)
                // If either is 0, result is 0
                emitRO("MUL", ac, ac1, ac, "op &&");
                emitRM("JEQ", ac, 2, pc, "br if false");
                emitRM("LDC", ac, 1, 0, "true case");
                emitRM("LDA", pc, 1, pc, "unconditional jmp");
                emitRM("LDC", ac, 0, 0, "false case");
                break;
                
            case OpExp.OR:
                // If either is non-zero, result is 1
                emitRO("ADD", ac, ac1, ac, "op ||");
                emitRM("JEQ", ac, 2, pc, "br if false");
                emitRM("LDC", ac, 1, 0, "true case");
                emitRM("LDA", pc, 1, pc, "unconditional jmp");
                emitRM("LDC", ac, 0, 0, "false case");
                break;
                
            case OpExp.NOT:
                // Unary operator - only right operand
                emitRM("JEQ", ac, 2, pc, "br if zero");
                emitRM("LDC", ac, 0, 0, "was true, now false");
                emitRM("LDA", pc, 1, pc, "unconditional jmp");
                emitRM("LDC", ac, 1, 0, "was false, now true");
                break;
                
            case OpExp.UMINUS:
                // Unary minus - negate right operand
                emitRM("LDC", ac1, 0, 0, "load 0");
                emitRO("SUB", ac, ac1, ac, "op unary -");
                break;
                
            default:
                emitComment("Unknown operator: " + exp.op);
                break;
        }
        
        emitComment("<- op");
    }
    
    public void visit(AssignExp exp, int level) {
        emitComment("-> op");
        
        // Visit LHS - need address
        emitComment("-> id");
        computingAddress = true;
        if (exp.lhs != null) {
            exp.lhs.accept(this, level);
        }
        computingAddress = false;
        emitComment("<- id");
        
        // Save address to temp location
        int tempOffset = level - 1;
        emitRM("ST", ac, tempOffset, fp, "op: push left");
        
        // Visit RHS - need value
        if (exp.rhs != null) {
            exp.rhs.accept(this, level - 2);
        }
        
        // Load address back
        emitRM("LD", ac1, tempOffset, fp, "op: load left");
        
        // Store value at address
        emitRM("ST", ac, 0, ac1, "assign: store value");
        
        emitComment("<- op");
    }
    
    public void visit(IfExp exp, int level) {
        emitComment("-> if");
        
        // Evaluate test condition
        if (exp.test != null) {
            exp.test.accept(this, level);
        }
        
        // Jump to else if test is false (will be backpatched)
        emitComment("if: jump to else belongs here");
        int jumpToElseLoc = emitSkip(1);
        
        // Generate then part
        if (exp.thenpart != null) {
            exp.thenpart.accept(this, level);
        }
        
        // Jump to end (skip else part) - will be backpatched
        emitComment("if: jump to end belongs here");
        int jumpToEndLoc = emitSkip(1);
        
        // Backpatch jump to else
        int elseLoc = emitLoc;
        emitBackup(jumpToElseLoc);
        emitRM("JEQ", ac, elseLoc - (jumpToElseLoc + 1), pc, "if: jmp to else");
        emitRestore();
        
        // Generate else part (if it exists)
        if (exp.elsepart != null) {
            exp.elsepart.accept(this, level);
        }
        
        // Backpatch jump to end
        int endLoc = emitLoc;
        emitBackup(jumpToEndLoc);
        emitRM_Abs("LDA", pc, endLoc, "jmp to end");
        emitRestore();
        
        emitComment("<- if");
    }
    
    public void visit(WhileExp exp, int level) {
        emitComment("-> while");
        
        // Save location of test (top of loop)
        int testLoc = emitLoc;
        emitComment("while: jump after body comes back here");
        
        // Evaluate test condition
        if (exp.test != null) {
            exp.test.accept(this, level);
        }
        
        // Jump to end if test is false (will be backpatched)
        emitComment("while: jump to end belongs here");
        int jumpToEndLoc = emitSkip(1);
        
        // Generate body
        if (exp.body != null) {
            exp.body.accept(this, level);
        }
        
        // Jump back to test
        emitRM_Abs("LDA", pc, testLoc, "while: absolute jmp to test");
        
        // Backpatch jump to end
        int endLoc = emitLoc;
        emitBackup(jumpToEndLoc);
        emitRM("JEQ", ac, endLoc - (jumpToEndLoc + 1), pc, "while: jmp to end");
        emitRestore();
        
        emitComment("<- while");
    }
    
    public void visit(ReturnExp exp, int level) {
        emitComment("-> return");
        
        // Evaluate return expression (if present)
        if (exp.exp != null) {
            exp.exp.accept(this, level);
            // Result is in ac
        }
        
        // Return to caller
        emitRM("LD", pc, retFO, fp, "return to caller");
        
        emitComment("<- return");
    }
    
    public void visit(NilExp exp, int level) {
        // No code generation needed
    }
}
